# Desarrollo Seguro de Aplicaciones
#Actividad 2 – Pipeline DevSecOps sobre euVWA
#Alumno: Raúl Miguel FernandesPipeline DevSecOps para euVWA
# La idea es automatizar controles básicos de seguridad cada vez que se sube código al repositorio.

name: DevSecOps Pipeline

# Se ejecuta automáticamente cuando hago push
# a las ramas principales del proyecto.
on:
  push:
    branches:
      - main
      - master
      - main-secure

jobs:
  security-pipeline:

    # GitHub crea una máquina Ubuntu temporal
    # donde se ejecutan todas las herramientas.
    runs-on: ubuntu-latest

    steps:

      # Descarga el contenido del repositorio.
      - name: Clonar repositorio
        uses: actions/checkout@v4

      # Instalación de Node.js.
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Instalación de dependencias del proyecto.
      - name: Instalar dependencias
        run: npm install

      # ESLint permite detectar problemas básicos
      # relacionados con seguridad en JavaScript.
      # El "|| true" evita detener el pipeline.
      - name: Ejecutar ESLint Security
        run: |
          npm install eslint eslint-plugin-security --save-dev
          npx eslint . || true

      # Semgrep realiza análisis SAST buscando
      # patrones inseguros directamente en el código.
      # Como euVWA es vulnerable intencionadamente,
      # permitimos continuar aunque encuentre fallos.
      - name: Ejecutar Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: "p/security-audit"

      # Construcción de la imagen Docker.
      - name: Construir imagen Docker
        run: docker build -t euvwa .

      # Escaneo de vulnerabilidades sobre
      # dependencias y archivos del proyecto.
      - name: Escaneo Trivy Filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

      # Escaneo de vulnerabilidades
      # dentro de la imagen Docker.
      - name: Escaneo Trivy Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: euvwa

      # Arranque temporal del contenedor
      # para realizar pruebas dinámicas.
      - name: Ejecutar aplicación
        run: |
          docker run -d -p 3000:3000 --name euvwa-container euvwa
          sleep 20

      # Escaneo DAST básico utilizando OWASP ZAP.
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: http://localhost:3000